import { MigrationInterface, QueryRunner } from "typeorm";

export class ReconcileSchemaToEntities1784454000000 implements MigrationInterface {
    name = 'ReconcileSchemaToEntities1784454000000'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "coupon_usages" DROP CONSTRAINT "FK_coupon_usages_order"`);
        await queryRunner.query(`ALTER TABLE "coupon_usages" DROP CONSTRAINT "FK_coupon_usages_user"`);
        await queryRunner.query(`ALTER TABLE "coupon_usages" DROP CONSTRAINT "FK_coupon_usages_coupon"`);
        await queryRunner.query(`ALTER TABLE "disputes" DROP CONSTRAINT "FK_disputes_order"`);
        await queryRunner.query(`ALTER TABLE "mfa_secrets" DROP CONSTRAINT "FK_mfa_secrets_user_id"`);
        await queryRunner.query(`ALTER TABLE "refund_approvals" DROP CONSTRAINT "FK_refund_approvals_order"`);
        await queryRunner.query(`ALTER TABLE "customer_subscriptions" DROP CONSTRAINT "FK_customer_subscriptions_plan"`);
        await queryRunner.query(`ALTER TABLE "customer_subscriptions" DROP CONSTRAINT "FK_customer_subscriptions_user"`);
        await queryRunner.query(`ALTER TABLE "restaurant_subscriptions" DROP CONSTRAINT "FK_restaurant_subscriptions_plan"`);
        await queryRunner.query(`ALTER TABLE "restaurant_subscriptions" DROP CONSTRAINT "FK_restaurant_subscriptions_restaurant"`);
        await queryRunner.query(`DROP INDEX "public"."idx_coupon_usages_coupon_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_coupon_usages_user_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_coupon_usages_order_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_driver_issues_driver_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_driver_issues_order_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_driver_issues_status"`);
        await queryRunner.query(`DROP INDEX "public"."idx_refund_approvals_order_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_tenants_slug"`);
        await queryRunner.query(`DROP INDEX "public"."idx_api_keys_key_hash"`);
        await queryRunner.query(`DROP INDEX "public"."idx_privacy_exports_user"`);
        await queryRunner.query(`DROP INDEX "public"."idx_privacy_exports_request"`);
        await queryRunner.query(`DROP INDEX "public"."idx_privacy_exports_status"`);
        await queryRunner.query(`DROP INDEX "public"."idx_retention_policies_key"`);
        await queryRunner.query(`DROP INDEX "public"."idx_cookie_registry_name"`);
        await queryRunner.query(`ALTER TABLE "legal_versions" DROP CONSTRAINT "UQ_legal_versions_doc_version"`);
        await queryRunner.query(`ALTER TABLE "ledger_entries" ADD "accountName" character varying`);
        await queryRunner.query(`ALTER TABLE "restaurant_subscriptions" ADD "billingCycle" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "bank_accounts" ADD "metadata" text`);
        await queryRunner.query(`ALTER TABLE "bank_accounts" ADD "restaurantId" uuid`);
        await queryRunner.query(`ALTER TABLE "bank_accounts" ADD "driverId" uuid`);
        await queryRunner.query(`ALTER TABLE "mfa_secrets" ALTER COLUMN "userId" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "mfa_secrets" ADD CONSTRAINT "UQ_9adff2630422d0325ec3369f6e0" UNIQUE ("userId")`);
        await queryRunner.query(`ALTER TABLE "delivery_pricing" DROP COLUMN "applicableDays"`);
        await queryRunner.query(`ALTER TABLE "delivery_pricing" ADD "applicableDays" text`);
        await queryRunner.query(`ALTER TABLE "delivery_pricing" DROP COLUMN "startTime"`);
        await queryRunner.query(`ALTER TABLE "delivery_pricing" ADD "startTime" TIME`);
        await queryRunner.query(`ALTER TABLE "delivery_pricing" DROP COLUMN "endTime"`);
        await queryRunner.query(`ALTER TABLE "delivery_pricing" ADD "endTime" TIME`);
        await queryRunner.query(`ALTER TABLE "api_keys" DROP CONSTRAINT "UQ_api_keys_key_hash"`);
        await queryRunner.query(`DROP INDEX "public"."idx_api_keys_user_id"`);
        await queryRunner.query(`ALTER TABLE "api_keys" DROP COLUMN "userId"`);
        await queryRunner.query(`ALTER TABLE "api_keys" ADD "userId" uuid NOT NULL`);
        await queryRunner.query(`DROP INDEX "public"."idx_api_keys_tenant_id"`);
        await queryRunner.query(`ALTER TABLE "api_keys" DROP COLUMN "tenantId"`);
        await queryRunner.query(`ALTER TABLE "api_keys" ADD "tenantId" uuid`);
        await queryRunner.query(`ALTER TABLE "api_keys" DROP COLUMN "scopes"`);
        await queryRunner.query(`ALTER TABLE "api_keys" ADD "scopes" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "bank_accounts" DROP COLUMN "tenantId"`);
        await queryRunner.query(`ALTER TABLE "bank_accounts" ADD "tenantId" uuid`);
        await queryRunner.query(`ALTER TABLE "legal_documents" ADD CONSTRAINT "UQ_910a98624cb5b53f2713173dc5a" UNIQUE ("type")`);
        await queryRunner.query(`ALTER TABLE "legal_documents" ALTER COLUMN "approvalStatus" SET DEFAULT 'pending'`);
        await queryRunner.query(`ALTER TABLE "legal_documents" ALTER COLUMN "multiLanguage" SET DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "legal_documents" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "legal_documents" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "legal_documents" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "legal_documents" ADD "updatedAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "legal_versions" DROP COLUMN "sections"`);
        await queryRunner.query(`ALTER TABLE "legal_versions" ADD "sections" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "legal_versions" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "legal_versions" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "legal_versions" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "legal_versions" ADD "updatedAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "legal_acceptances" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "legal_acceptances" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "cookie_consents" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "cookie_consents" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "cookie_consents" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "cookie_consents" ADD "updatedAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "consent_logs" DROP COLUMN "metadata"`);
        await queryRunner.query(`ALTER TABLE "consent_logs" ADD "metadata" text`);
        await queryRunner.query(`DROP INDEX "public"."idx_consent_logs_created"`);
        await queryRunner.query(`ALTER TABLE "consent_logs" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "consent_logs" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "data_subject_requests" DROP COLUMN "metadata"`);
        await queryRunner.query(`ALTER TABLE "data_subject_requests" ADD "metadata" text`);
        await queryRunner.query(`ALTER TABLE "data_subject_requests" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "data_subject_requests" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "data_subject_requests" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "data_subject_requests" ADD "updatedAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "privacy_data_exports" ADD CONSTRAINT "PK_c0131e46633c27e3aca686c8d10" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "privacy_data_exports" DROP COLUMN "scope"`);
        await queryRunner.query(`ALTER TABLE "privacy_data_exports" ADD "scope" text`);
        await queryRunner.query(`ALTER TABLE "privacy_data_exports" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "privacy_data_exports" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "privacy_data_exports" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "privacy_data_exports" ADD "updatedAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "retention_policies" DROP COLUMN "scope"`);
        await queryRunner.query(`ALTER TABLE "retention_policies" ADD "scope" text`);
        await queryRunner.query(`ALTER TABLE "retention_policies" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "retention_policies" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "retention_policies" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "retention_policies" ADD "updatedAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "data_retention_jobs" ADD CONSTRAINT "PK_fe5f55ac863c2e4d9a4d22f8b36" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "data_retention_jobs" DROP COLUMN "result"`);
        await queryRunner.query(`ALTER TABLE "data_retention_jobs" ADD "result" text`);
        await queryRunner.query(`ALTER TABLE "data_retention_jobs" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "data_retention_jobs" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "data_retention_jobs" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "data_retention_jobs" ADD "updatedAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "security_incidents" DROP COLUMN "affectedSystems"`);
        await queryRunner.query(`ALTER TABLE "security_incidents" ADD "affectedSystems" text`);
        await queryRunner.query(`ALTER TABLE "security_incidents" DROP COLUMN "remediationSteps"`);
        await queryRunner.query(`ALTER TABLE "security_incidents" ADD "remediationSteps" text`);
        await queryRunner.query(`DROP INDEX "public"."idx_security_incidents_created"`);
        await queryRunner.query(`ALTER TABLE "security_incidents" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "security_incidents" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "security_incidents" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "security_incidents" ADD "updatedAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "grievances" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "grievances" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "grievances" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "grievances" ADD "updatedAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "agreements" DROP COLUMN "clauses"`);
        await queryRunner.query(`ALTER TABLE "agreements" ADD "clauses" text`);
        await queryRunner.query(`ALTER TABLE "agreements" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "agreements" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "agreements" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "agreements" ADD "updatedAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "agreement_acceptances" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "agreement_acceptances" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "compliance_audits" DROP COLUMN "metadata"`);
        await queryRunner.query(`ALTER TABLE "compliance_audits" ADD "metadata" text`);
        await queryRunner.query(`DROP INDEX "public"."idx_compliance_audits_created"`);
        await queryRunner.query(`ALTER TABLE "compliance_audits" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "compliance_audits" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "cookie_registry" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "cookie_registry" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "cookie_registry" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "cookie_registry" ADD "updatedAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`CREATE UNIQUE INDEX "idx_tenants_slug" ON "tenants" ("slug") `);
        await queryRunner.query(`CREATE INDEX "idx_api_keys_tenant_id" ON "api_keys" ("tenantId") `);
        await queryRunner.query(`CREATE INDEX "idx_api_keys_user_id" ON "api_keys" ("userId") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "idx_api_keys_key_hash" ON "api_keys" ("keyHash") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "idx_legal_versions_document_version" ON "legal_versions" ("documentId", "version") `);
        await queryRunner.query(`CREATE INDEX "idx_consent_logs_created" ON "consent_logs" ("createdAt") `);
        await queryRunner.query(`CREATE INDEX "idx_data_exports_status" ON "privacy_data_exports" ("status") `);
        await queryRunner.query(`CREATE INDEX "idx_data_exports_request" ON "privacy_data_exports" ("requestId") `);
        await queryRunner.query(`CREATE INDEX "idx_data_exports_user" ON "privacy_data_exports" ("userId") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "idx_retention_policies_key" ON "retention_policies" ("key") `);
        await queryRunner.query(`CREATE INDEX "idx_security_incidents_created" ON "security_incidents" ("createdAt") `);
        await queryRunner.query(`CREATE INDEX "idx_compliance_audits_created" ON "compliance_audits" ("createdAt") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "idx_cookie_registry_name" ON "cookie_registry" ("name") `);
        await queryRunner.query(`ALTER TABLE "mfa_secrets" ADD CONSTRAINT "FK_9adff2630422d0325ec3369f6e0" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "customer_subscriptions" ADD CONSTRAINT "FK_c43ea82fd0576ead7c58961d79e" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "customer_subscriptions" ADD CONSTRAINT "FK_6d11b75e0b41c14f6ba720f9a50" FOREIGN KEY ("planId") REFERENCES "subscription_plans"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "restaurant_subscriptions" ADD CONSTRAINT "FK_b63236e856d8cbab449ad6f7f8b" FOREIGN KEY ("restaurantId") REFERENCES "restaurants"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "restaurant_subscriptions" ADD CONSTRAINT "FK_662d78fa5611204a927286d60b3" FOREIGN KEY ("planId") REFERENCES "subscription_plans"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "api_keys" ADD CONSTRAINT "FK_6c2e267ae764a9413b863a29342" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "api_keys" ADD CONSTRAINT "FK_2cd545077d6e6e8378b051cf1b7" FOREIGN KEY ("tenantId") REFERENCES "tenants"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "bank_accounts" ADD CONSTRAINT "FK_f9c2fdfa7a1f73a89dad85afaac" FOREIGN KEY ("restaurantId") REFERENCES "restaurants"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "bank_accounts" ADD CONSTRAINT "FK_a43e289e9dd9afb3d76bf275f13" FOREIGN KEY ("driverId") REFERENCES "drivers"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "bank_accounts" ADD CONSTRAINT "FK_56cb500b41e924b1fadc5051d5d" FOREIGN KEY ("tenantId") REFERENCES "tenants"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "bank_accounts" DROP CONSTRAINT "FK_56cb500b41e924b1fadc5051d5d"`);
        await queryRunner.query(`ALTER TABLE "bank_accounts" DROP CONSTRAINT "FK_a43e289e9dd9afb3d76bf275f13"`);
        await queryRunner.query(`ALTER TABLE "bank_accounts" DROP CONSTRAINT "FK_f9c2fdfa7a1f73a89dad85afaac"`);
        await queryRunner.query(`ALTER TABLE "api_keys" DROP CONSTRAINT "FK_2cd545077d6e6e8378b051cf1b7"`);
        await queryRunner.query(`ALTER TABLE "api_keys" DROP CONSTRAINT "FK_6c2e267ae764a9413b863a29342"`);
        await queryRunner.query(`ALTER TABLE "restaurant_subscriptions" DROP CONSTRAINT "FK_662d78fa5611204a927286d60b3"`);
        await queryRunner.query(`ALTER TABLE "restaurant_subscriptions" DROP CONSTRAINT "FK_b63236e856d8cbab449ad6f7f8b"`);
        await queryRunner.query(`ALTER TABLE "customer_subscriptions" DROP CONSTRAINT "FK_6d11b75e0b41c14f6ba720f9a50"`);
        await queryRunner.query(`ALTER TABLE "customer_subscriptions" DROP CONSTRAINT "FK_c43ea82fd0576ead7c58961d79e"`);
        await queryRunner.query(`ALTER TABLE "mfa_secrets" DROP CONSTRAINT "FK_9adff2630422d0325ec3369f6e0"`);
        await queryRunner.query(`DROP INDEX "public"."idx_cookie_registry_name"`);
        await queryRunner.query(`DROP INDEX "public"."idx_compliance_audits_created"`);
        await queryRunner.query(`DROP INDEX "public"."idx_security_incidents_created"`);
        await queryRunner.query(`DROP INDEX "public"."idx_retention_policies_key"`);
        await queryRunner.query(`DROP INDEX "public"."idx_data_exports_user"`);
        await queryRunner.query(`DROP INDEX "public"."idx_data_exports_request"`);
        await queryRunner.query(`DROP INDEX "public"."idx_data_exports_status"`);
        await queryRunner.query(`DROP INDEX "public"."idx_consent_logs_created"`);
        await queryRunner.query(`DROP INDEX "public"."idx_legal_versions_document_version"`);
        await queryRunner.query(`DROP INDEX "public"."idx_api_keys_key_hash"`);
        await queryRunner.query(`DROP INDEX "public"."idx_api_keys_user_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_api_keys_tenant_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_tenants_slug"`);
        await queryRunner.query(`ALTER TABLE "cookie_registry" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "cookie_registry" ADD "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "cookie_registry" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "cookie_registry" ADD "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "compliance_audits" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "compliance_audits" ADD "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`CREATE INDEX "idx_compliance_audits_created" ON "compliance_audits" ("createdAt") `);
        await queryRunner.query(`ALTER TABLE "compliance_audits" DROP COLUMN "metadata"`);
        await queryRunner.query(`ALTER TABLE "compliance_audits" ADD "metadata" jsonb`);
        await queryRunner.query(`ALTER TABLE "agreement_acceptances" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "agreement_acceptances" ADD "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "agreements" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "agreements" ADD "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "agreements" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "agreements" ADD "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "agreements" DROP COLUMN "clauses"`);
        await queryRunner.query(`ALTER TABLE "agreements" ADD "clauses" jsonb`);
        await queryRunner.query(`ALTER TABLE "grievances" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "grievances" ADD "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "grievances" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "grievances" ADD "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "security_incidents" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "security_incidents" ADD "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "security_incidents" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "security_incidents" ADD "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`CREATE INDEX "idx_security_incidents_created" ON "security_incidents" ("createdAt") `);
        await queryRunner.query(`ALTER TABLE "security_incidents" DROP COLUMN "remediationSteps"`);
        await queryRunner.query(`ALTER TABLE "security_incidents" ADD "remediationSteps" jsonb`);
        await queryRunner.query(`ALTER TABLE "security_incidents" DROP COLUMN "affectedSystems"`);
        await queryRunner.query(`ALTER TABLE "security_incidents" ADD "affectedSystems" jsonb`);
        await queryRunner.query(`ALTER TABLE "data_retention_jobs" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "data_retention_jobs" ADD "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "data_retention_jobs" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "data_retention_jobs" ADD "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "data_retention_jobs" DROP COLUMN "result"`);
        await queryRunner.query(`ALTER TABLE "data_retention_jobs" ADD "result" jsonb`);
        await queryRunner.query(`ALTER TABLE "data_retention_jobs" DROP CONSTRAINT "PK_fe5f55ac863c2e4d9a4d22f8b36"`);
        await queryRunner.query(`ALTER TABLE "retention_policies" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "retention_policies" ADD "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "retention_policies" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "retention_policies" ADD "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "retention_policies" DROP COLUMN "scope"`);
        await queryRunner.query(`ALTER TABLE "retention_policies" ADD "scope" jsonb`);
        await queryRunner.query(`ALTER TABLE "privacy_data_exports" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "privacy_data_exports" ADD "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "privacy_data_exports" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "privacy_data_exports" ADD "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "privacy_data_exports" DROP COLUMN "scope"`);
        await queryRunner.query(`ALTER TABLE "privacy_data_exports" ADD "scope" jsonb`);
        await queryRunner.query(`ALTER TABLE "privacy_data_exports" DROP CONSTRAINT "PK_c0131e46633c27e3aca686c8d10"`);
        await queryRunner.query(`ALTER TABLE "data_subject_requests" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "data_subject_requests" ADD "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "data_subject_requests" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "data_subject_requests" ADD "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "data_subject_requests" DROP COLUMN "metadata"`);
        await queryRunner.query(`ALTER TABLE "data_subject_requests" ADD "metadata" jsonb`);
        await queryRunner.query(`ALTER TABLE "consent_logs" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "consent_logs" ADD "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`CREATE INDEX "idx_consent_logs_created" ON "consent_logs" ("createdAt") `);
        await queryRunner.query(`ALTER TABLE "consent_logs" DROP COLUMN "metadata"`);
        await queryRunner.query(`ALTER TABLE "consent_logs" ADD "metadata" jsonb`);
        await queryRunner.query(`ALTER TABLE "cookie_consents" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "cookie_consents" ADD "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "cookie_consents" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "cookie_consents" ADD "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "legal_acceptances" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "legal_acceptances" ADD "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "legal_versions" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "legal_versions" ADD "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "legal_versions" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "legal_versions" ADD "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "legal_versions" DROP COLUMN "sections"`);
        await queryRunner.query(`ALTER TABLE "legal_versions" ADD "sections" jsonb NOT NULL`);
        await queryRunner.query(`ALTER TABLE "legal_documents" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "legal_documents" ADD "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "legal_documents" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "legal_documents" ADD "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "legal_documents" ALTER COLUMN "multiLanguage" SET DEFAULT true`);
        await queryRunner.query(`ALTER TABLE "legal_documents" ALTER COLUMN "approvalStatus" SET DEFAULT 'approved'`);
        await queryRunner.query(`ALTER TABLE "legal_documents" DROP CONSTRAINT "UQ_910a98624cb5b53f2713173dc5a"`);
        await queryRunner.query(`ALTER TABLE "bank_accounts" DROP COLUMN "tenantId"`);
        await queryRunner.query(`ALTER TABLE "bank_accounts" ADD "tenantId" character varying`);
        await queryRunner.query(`ALTER TABLE "api_keys" DROP COLUMN "scopes"`);
        await queryRunner.query(`ALTER TABLE "api_keys" ADD "scopes" character varying array NOT NULL`);
        await queryRunner.query(`ALTER TABLE "api_keys" DROP COLUMN "tenantId"`);
        await queryRunner.query(`ALTER TABLE "api_keys" ADD "tenantId" character varying`);
        await queryRunner.query(`CREATE INDEX "idx_api_keys_tenant_id" ON "api_keys" ("tenantId") `);
        await queryRunner.query(`ALTER TABLE "api_keys" DROP COLUMN "userId"`);
        await queryRunner.query(`ALTER TABLE "api_keys" ADD "userId" character varying NOT NULL`);
        await queryRunner.query(`CREATE INDEX "idx_api_keys_user_id" ON "api_keys" ("userId") `);
        await queryRunner.query(`ALTER TABLE "api_keys" ADD CONSTRAINT "UQ_api_keys_key_hash" UNIQUE ("keyHash")`);
        await queryRunner.query(`ALTER TABLE "delivery_pricing" DROP COLUMN "endTime"`);
        await queryRunner.query(`ALTER TABLE "delivery_pricing" ADD "endTime" character varying`);
        await queryRunner.query(`ALTER TABLE "delivery_pricing" DROP COLUMN "startTime"`);
        await queryRunner.query(`ALTER TABLE "delivery_pricing" ADD "startTime" character varying`);
        await queryRunner.query(`ALTER TABLE "delivery_pricing" DROP COLUMN "applicableDays"`);
        await queryRunner.query(`ALTER TABLE "delivery_pricing" ADD "applicableDays" character varying array`);
        await queryRunner.query(`ALTER TABLE "mfa_secrets" DROP CONSTRAINT "UQ_9adff2630422d0325ec3369f6e0"`);
        await queryRunner.query(`ALTER TABLE "mfa_secrets" ALTER COLUMN "userId" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "bank_accounts" DROP COLUMN "driverId"`);
        await queryRunner.query(`ALTER TABLE "bank_accounts" DROP COLUMN "restaurantId"`);
        await queryRunner.query(`ALTER TABLE "bank_accounts" DROP COLUMN "metadata"`);
        await queryRunner.query(`ALTER TABLE "restaurant_subscriptions" DROP COLUMN "billingCycle"`);
        await queryRunner.query(`ALTER TABLE "ledger_entries" DROP COLUMN "accountName"`);
        await queryRunner.query(`ALTER TABLE "legal_versions" ADD CONSTRAINT "UQ_legal_versions_doc_version" UNIQUE ("documentId", "version")`);
        await queryRunner.query(`CREATE INDEX "idx_cookie_registry_name" ON "cookie_registry" ("name") `);
        await queryRunner.query(`CREATE INDEX "idx_retention_policies_key" ON "retention_policies" ("key") `);
        await queryRunner.query(`CREATE INDEX "idx_privacy_exports_status" ON "privacy_data_exports" ("status") `);
        await queryRunner.query(`CREATE INDEX "idx_privacy_exports_request" ON "privacy_data_exports" ("requestId") `);
        await queryRunner.query(`CREATE INDEX "idx_privacy_exports_user" ON "privacy_data_exports" ("userId") `);
        await queryRunner.query(`CREATE INDEX "idx_api_keys_key_hash" ON "api_keys" ("keyHash") `);
        await queryRunner.query(`CREATE INDEX "idx_tenants_slug" ON "tenants" ("slug") `);
        await queryRunner.query(`CREATE INDEX "idx_refund_approvals_order_id" ON "refund_approvals" ("orderId") `);
        await queryRunner.query(`CREATE INDEX "idx_driver_issues_status" ON "driver_issues" ("status") `);
        await queryRunner.query(`CREATE INDEX "idx_driver_issues_order_id" ON "driver_issues" ("orderId") `);
        await queryRunner.query(`CREATE INDEX "idx_driver_issues_driver_id" ON "driver_issues" ("driverId") `);
        await queryRunner.query(`CREATE INDEX "idx_coupon_usages_order_id" ON "coupon_usages" ("orderId") `);
        await queryRunner.query(`CREATE INDEX "idx_coupon_usages_user_id" ON "coupon_usages" ("userId") `);
        await queryRunner.query(`CREATE INDEX "idx_coupon_usages_coupon_id" ON "coupon_usages" ("couponId") `);
        await queryRunner.query(`ALTER TABLE "restaurant_subscriptions" ADD CONSTRAINT "FK_restaurant_subscriptions_restaurant" FOREIGN KEY ("restaurantId") REFERENCES "restaurants"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "restaurant_subscriptions" ADD CONSTRAINT "FK_restaurant_subscriptions_plan" FOREIGN KEY ("planId") REFERENCES "subscription_plans"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "customer_subscriptions" ADD CONSTRAINT "FK_customer_subscriptions_user" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "customer_subscriptions" ADD CONSTRAINT "FK_customer_subscriptions_plan" FOREIGN KEY ("planId") REFERENCES "subscription_plans"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "refund_approvals" ADD CONSTRAINT "FK_refund_approvals_order" FOREIGN KEY ("orderId") REFERENCES "orders"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "mfa_secrets" ADD CONSTRAINT "FK_mfa_secrets_user_id" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "disputes" ADD CONSTRAINT "FK_disputes_order" FOREIGN KEY ("orderId") REFERENCES "orders"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "coupon_usages" ADD CONSTRAINT "FK_coupon_usages_coupon" FOREIGN KEY ("couponId") REFERENCES "coupons"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "coupon_usages" ADD CONSTRAINT "FK_coupon_usages_user" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "coupon_usages" ADD CONSTRAINT "FK_coupon_usages_order" FOREIGN KEY ("orderId") REFERENCES "orders"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

}
