"use strict";
var __esDecorate = (this && this.__esDecorate) || function (ctor, descriptorIn, decorators, contextIn, initializers, extraInitializers) {
    function accept(f) { if (f !== void 0 && typeof f !== "function") throw new TypeError("Function expected"); return f; }
    var kind = contextIn.kind, key = kind === "getter" ? "get" : kind === "setter" ? "set" : "value";
    var target = !descriptorIn && ctor ? contextIn["static"] ? ctor : ctor.prototype : null;
    var descriptor = descriptorIn || (target ? Object.getOwnPropertyDescriptor(target, contextIn.name) : {});
    var _, done = false;
    for (var i = decorators.length - 1; i >= 0; i--) {
        var context = {};
        for (var p in contextIn) context[p] = p === "access" ? {} : contextIn[p];
        for (var p in contextIn.access) context.access[p] = contextIn.access[p];
        context.addInitializer = function (f) { if (done) throw new TypeError("Cannot add initializers after decoration has completed"); extraInitializers.push(accept(f || null)); };
        var result = (0, decorators[i])(kind === "accessor" ? { get: descriptor.get, set: descriptor.set } : descriptor[key], context);
        if (kind === "accessor") {
            if (result === void 0) continue;
            if (result === null || typeof result !== "object") throw new TypeError("Object expected");
            if (_ = accept(result.get)) descriptor.get = _;
            if (_ = accept(result.set)) descriptor.set = _;
            if (_ = accept(result.init)) initializers.unshift(_);
        }
        else if (_ = accept(result)) {
            if (kind === "field") initializers.unshift(_);
            else descriptor[key] = _;
        }
    }
    if (target) Object.defineProperty(target, contextIn.name, descriptor);
    done = true;
};
var __runInitializers = (this && this.__runInitializers) || function (thisArg, initializers, value) {
    var useValue = arguments.length > 2;
    for (var i = 0; i < initializers.length; i++) {
        value = useValue ? initializers[i].call(thisArg, value) : initializers[i].call(thisArg);
    }
    return useValue ? value : void 0;
};
var __setFunctionName = (this && this.__setFunctionName) || function (f, name, prefix) {
    if (typeof name === "symbol") name = name.description ? "[".concat(name.description, "]") : "";
    return Object.defineProperty(f, "name", { configurable: true, value: prefix ? "".concat(prefix, " ", name) : name });
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.OrderEntity = void 0;
var typeorm_1 = require("typeorm");
var order_interface_1 = require("../../shared/domain/order.interface");
var order_item_entity_1 = require("./order-item.entity");
var gst_detail_entity_1 = require("./gst-detail.entity");
var restaurant_branch_entity_1 = require("./restaurant-branch.entity");
var OrderEntity = function () {
    var _classDecorators = [(0, typeorm_1.Entity)('orders')];
    var _classDescriptor;
    var _classExtraInitializers = [];
    var _classThis;
    var _instanceExtraInitializers = [];
    var _id_decorators;
    var _id_initializers = [];
    var _items_decorators;
    var _items_initializers = [];
    var _userId_decorators;
    var _userId_initializers = [];
    var _restaurantId_decorators;
    var _restaurantId_initializers = [];
    var _branchId_decorators;
    var _branchId_initializers = [];
    var _branch_decorators;
    var _branch_initializers = [];
    var _driverId_decorators;
    var _driverId_initializers = [];
    var _orderNumber_decorators;
    var _orderNumber_initializers = [];
    var _status_decorators;
    var _status_initializers = [];
    var _paymentStatus_decorators;
    var _paymentStatus_initializers = [];
    var _paymentIntentId_decorators;
    var _paymentIntentId_initializers = [];
    var _subtotal_decorators;
    var _subtotal_initializers = [];
    var _tax_decorators;
    var _tax_initializers = [];
    var _deliveryFee_decorators;
    var _deliveryFee_initializers = [];
    var _discount_decorators;
    var _discount_initializers = [];
    var _tip_decorators;
    var _tip_initializers = [];
    var _grandTotal_decorators;
    var _grandTotal_initializers = [];
    var _couponId_decorators;
    var _couponId_initializers = [];
    var _otpCode_decorators;
    var _otpCode_initializers = [];
    var _deliveryAddressId_decorators;
    var _deliveryAddressId_initializers = [];
    var _gstDetail_decorators;
    var _gstDetail_initializers = [];
    var _createdAt_decorators;
    var _createdAt_initializers = [];
    var _updatedAt_decorators;
    var _updatedAt_initializers = [];
    var _deliveredAt_decorators;
    var _deliveredAt_initializers = [];
    var _itemsHash_decorators;
    var _itemsHash_initializers = [];
    var _refundedAmount_decorators;
    var _refundedAmount_initializers = [];
    var OrderEntity = _classThis = /** @class */ (function () {
        function OrderEntity_1() {
            this.id = (__runInitializers(this, _instanceExtraInitializers), __runInitializers(this, _id_initializers, void 0));
            this.items = __runInitializers(this, _items_initializers, void 0);
            this.userId = __runInitializers(this, _userId_initializers, void 0);
            this.restaurantId = __runInitializers(this, _restaurantId_initializers, void 0);
            this.branchId = __runInitializers(this, _branchId_initializers, void 0);
            this.branch = __runInitializers(this, _branch_initializers, void 0);
            this.driverId = __runInitializers(this, _driverId_initializers, void 0);
            this.orderNumber = __runInitializers(this, _orderNumber_initializers, void 0);
            this.status = __runInitializers(this, _status_initializers, void 0);
            this.paymentStatus = __runInitializers(this, _paymentStatus_initializers, void 0);
            this.paymentIntentId = __runInitializers(this, _paymentIntentId_initializers, void 0);
            this.subtotal = __runInitializers(this, _subtotal_initializers, void 0);
            this.tax = __runInitializers(this, _tax_initializers, void 0);
            this.deliveryFee = __runInitializers(this, _deliveryFee_initializers, void 0);
            this.discount = __runInitializers(this, _discount_initializers, void 0);
            this.tip = __runInitializers(this, _tip_initializers, void 0);
            this.grandTotal = __runInitializers(this, _grandTotal_initializers, void 0);
            this.couponId = __runInitializers(this, _couponId_initializers, void 0);
            this.otpCode = __runInitializers(this, _otpCode_initializers, void 0);
            this.deliveryAddressId = __runInitializers(this, _deliveryAddressId_initializers, void 0);
            this.gstDetail = __runInitializers(this, _gstDetail_initializers, void 0);
            this.createdAt = __runInitializers(this, _createdAt_initializers, void 0);
            this.updatedAt = __runInitializers(this, _updatedAt_initializers, void 0);
            this.deliveredAt = __runInitializers(this, _deliveredAt_initializers, void 0);
            this.itemsHash = __runInitializers(this, _itemsHash_initializers, void 0);
            this.refundedAmount = __runInitializers(this, _refundedAmount_initializers, void 0);
        }
        return OrderEntity_1;
    }());
    __setFunctionName(_classThis, "OrderEntity");
    (function () {
        var _metadata = typeof Symbol === "function" && Symbol.metadata ? Object.create(null) : void 0;
        _id_decorators = [(0, typeorm_1.PrimaryGeneratedColumn)('uuid')];
        _items_decorators = [(0, typeorm_1.OneToMany)(function () { return order_item_entity_1.OrderItemEntity; }, function (item) { return item.order; })];
        _userId_decorators = [(0, typeorm_1.Column)()];
        _restaurantId_decorators = [(0, typeorm_1.Column)()];
        _branchId_decorators = [(0, typeorm_1.Column)({ nullable: true })];
        _branch_decorators = [(0, typeorm_1.ManyToOne)(function () { return restaurant_branch_entity_1.RestaurantBranchEntity; })];
        _driverId_decorators = [(0, typeorm_1.Column)({ nullable: true })];
        _orderNumber_decorators = [(0, typeorm_1.Column)()];
        _status_decorators = [(0, typeorm_1.Column)({ type: 'enum', enum: order_interface_1.OrderStatus, default: order_interface_1.OrderStatus.PLACED })];
        _paymentStatus_decorators = [(0, typeorm_1.Column)({ type: 'enum', enum: order_interface_1.PaymentStatus, default: order_interface_1.PaymentStatus.PENDING })];
        _paymentIntentId_decorators = [(0, typeorm_1.Column)({ nullable: true })];
        _subtotal_decorators = [(0, typeorm_1.Column)('decimal', { precision: 10, scale: 2 })];
        _tax_decorators = [(0, typeorm_1.Column)('decimal', { precision: 10, scale: 2 })];
        _deliveryFee_decorators = [(0, typeorm_1.Column)('decimal', { precision: 10, scale: 2 })];
        _discount_decorators = [(0, typeorm_1.Column)('decimal', { precision: 10, scale: 2 })];
        _tip_decorators = [(0, typeorm_1.Column)('decimal', { precision: 10, scale: 2 })];
        _grandTotal_decorators = [(0, typeorm_1.Column)('decimal', { precision: 10, scale: 2 })];
        _couponId_decorators = [(0, typeorm_1.Column)({ nullable: true })];
        _otpCode_decorators = [(0, typeorm_1.Column)({ nullable: true })];
        _deliveryAddressId_decorators = [(0, typeorm_1.Column)()];
        _gstDetail_decorators = [(0, typeorm_1.OneToOne)(function () { return gst_detail_entity_1.GSTDetailEntity; }, function (gstDetail) { return gstDetail.order; })];
        _createdAt_decorators = [(0, typeorm_1.CreateDateColumn)()];
        _updatedAt_decorators = [(0, typeorm_1.UpdateDateColumn)()];
        _deliveredAt_decorators = [(0, typeorm_1.Column)({ nullable: true })];
        _itemsHash_decorators = [(0, typeorm_1.Column)({ nullable: true })];
        _refundedAmount_decorators = [(0, typeorm_1.Column)('decimal', { precision: 10, scale: 2, default: 0, name: 'refunded_amount' })];
        __esDecorate(null, null, _id_decorators, { kind: "field", name: "id", static: false, private: false, access: { has: function (obj) { return "id" in obj; }, get: function (obj) { return obj.id; }, set: function (obj, value) { obj.id = value; } }, metadata: _metadata }, _id_initializers, _instanceExtraInitializers);
        __esDecorate(null, null, _items_decorators, { kind: "field", name: "items", static: false, private: false, access: { has: function (obj) { return "items" in obj; }, get: function (obj) { return obj.items; }, set: function (obj, value) { obj.items = value; } }, metadata: _metadata }, _items_initializers, _instanceExtraInitializers);
        __esDecorate(null, null, _userId_decorators, { kind: "field", name: "userId", static: false, private: false, access: { has: function (obj) { return "userId" in obj; }, get: function (obj) { return obj.userId; }, set: function (obj, value) { obj.userId = value; } }, metadata: _metadata }, _userId_initializers, _instanceExtraInitializers);
        __esDecorate(null, null, _restaurantId_decorators, { kind: "field", name: "restaurantId", static: false, private: false, access: { has: function (obj) { return "restaurantId" in obj; }, get: function (obj) { return obj.restaurantId; }, set: function (obj, value) { obj.restaurantId = value; } }, metadata: _metadata }, _restaurantId_initializers, _instanceExtraInitializers);
        __esDecorate(null, null, _branchId_decorators, { kind: "field", name: "branchId", static: false, private: false, access: { has: function (obj) { return "branchId" in obj; }, get: function (obj) { return obj.branchId; }, set: function (obj, value) { obj.branchId = value; } }, metadata: _metadata }, _branchId_initializers, _instanceExtraInitializers);
        __esDecorate(null, null, _branch_decorators, { kind: "field", name: "branch", static: false, private: false, access: { has: function (obj) { return "branch" in obj; }, get: function (obj) { return obj.branch; }, set: function (obj, value) { obj.branch = value; } }, metadata: _metadata }, _branch_initializers, _instanceExtraInitializers);
        __esDecorate(null, null, _driverId_decorators, { kind: "field", name: "driverId", static: false, private: false, access: { has: function (obj) { return "driverId" in obj; }, get: function (obj) { return obj.driverId; }, set: function (obj, value) { obj.driverId = value; } }, metadata: _metadata }, _driverId_initializers, _instanceExtraInitializers);
        __esDecorate(null, null, _orderNumber_decorators, { kind: "field", name: "orderNumber", static: false, private: false, access: { has: function (obj) { return "orderNumber" in obj; }, get: function (obj) { return obj.orderNumber; }, set: function (obj, value) { obj.orderNumber = value; } }, metadata: _metadata }, _orderNumber_initializers, _instanceExtraInitializers);
        __esDecorate(null, null, _status_decorators, { kind: "field", name: "status", static: false, private: false, access: { has: function (obj) { return "status" in obj; }, get: function (obj) { return obj.status; }, set: function (obj, value) { obj.status = value; } }, metadata: _metadata }, _status_initializers, _instanceExtraInitializers);
        __esDecorate(null, null, _paymentStatus_decorators, { kind: "field", name: "paymentStatus", static: false, private: false, access: { has: function (obj) { return "paymentStatus" in obj; }, get: function (obj) { return obj.paymentStatus; }, set: function (obj, value) { obj.paymentStatus = value; } }, metadata: _metadata }, _paymentStatus_initializers, _instanceExtraInitializers);
        __esDecorate(null, null, _paymentIntentId_decorators, { kind: "field", name: "paymentIntentId", static: false, private: false, access: { has: function (obj) { return "paymentIntentId" in obj; }, get: function (obj) { return obj.paymentIntentId; }, set: function (obj, value) { obj.paymentIntentId = value; } }, metadata: _metadata }, _paymentIntentId_initializers, _instanceExtraInitializers);
        __esDecorate(null, null, _subtotal_decorators, { kind: "field", name: "subtotal", static: false, private: false, access: { has: function (obj) { return "subtotal" in obj; }, get: function (obj) { return obj.subtotal; }, set: function (obj, value) { obj.subtotal = value; } }, metadata: _metadata }, _subtotal_initializers, _instanceExtraInitializers);
        __esDecorate(null, null, _tax_decorators, { kind: "field", name: "tax", static: false, private: false, access: { has: function (obj) { return "tax" in obj; }, get: function (obj) { return obj.tax; }, set: function (obj, value) { obj.tax = value; } }, metadata: _metadata }, _tax_initializers, _instanceExtraInitializers);
        __esDecorate(null, null, _deliveryFee_decorators, { kind: "field", name: "deliveryFee", static: false, private: false, access: { has: function (obj) { return "deliveryFee" in obj; }, get: function (obj) { return obj.deliveryFee; }, set: function (obj, value) { obj.deliveryFee = value; } }, metadata: _metadata }, _deliveryFee_initializers, _instanceExtraInitializers);
        __esDecorate(null, null, _discount_decorators, { kind: "field", name: "discount", static: false, private: false, access: { has: function (obj) { return "discount" in obj; }, get: function (obj) { return obj.discount; }, set: function (obj, value) { obj.discount = value; } }, metadata: _metadata }, _discount_initializers, _instanceExtraInitializers);
        __esDecorate(null, null, _tip_decorators, { kind: "field", name: "tip", static: false, private: false, access: { has: function (obj) { return "tip" in obj; }, get: function (obj) { return obj.tip; }, set: function (obj, value) { obj.tip = value; } }, metadata: _metadata }, _tip_initializers, _instanceExtraInitializers);
        __esDecorate(null, null, _grandTotal_decorators, { kind: "field", name: "grandTotal", static: false, private: false, access: { has: function (obj) { return "grandTotal" in obj; }, get: function (obj) { return obj.grandTotal; }, set: function (obj, value) { obj.grandTotal = value; } }, metadata: _metadata }, _grandTotal_initializers, _instanceExtraInitializers);
        __esDecorate(null, null, _couponId_decorators, { kind: "field", name: "couponId", static: false, private: false, access: { has: function (obj) { return "couponId" in obj; }, get: function (obj) { return obj.couponId; }, set: function (obj, value) { obj.couponId = value; } }, metadata: _metadata }, _couponId_initializers, _instanceExtraInitializers);
        __esDecorate(null, null, _otpCode_decorators, { kind: "field", name: "otpCode", static: false, private: false, access: { has: function (obj) { return "otpCode" in obj; }, get: function (obj) { return obj.otpCode; }, set: function (obj, value) { obj.otpCode = value; } }, metadata: _metadata }, _otpCode_initializers, _instanceExtraInitializers);
        __esDecorate(null, null, _deliveryAddressId_decorators, { kind: "field", name: "deliveryAddressId", static: false, private: false, access: { has: function (obj) { return "deliveryAddressId" in obj; }, get: function (obj) { return obj.deliveryAddressId; }, set: function (obj, value) { obj.deliveryAddressId = value; } }, metadata: _metadata }, _deliveryAddressId_initializers, _instanceExtraInitializers);
        __esDecorate(null, null, _gstDetail_decorators, { kind: "field", name: "gstDetail", static: false, private: false, access: { has: function (obj) { return "gstDetail" in obj; }, get: function (obj) { return obj.gstDetail; }, set: function (obj, value) { obj.gstDetail = value; } }, metadata: _metadata }, _gstDetail_initializers, _instanceExtraInitializers);
        __esDecorate(null, null, _createdAt_decorators, { kind: "field", name: "createdAt", static: false, private: false, access: { has: function (obj) { return "createdAt" in obj; }, get: function (obj) { return obj.createdAt; }, set: function (obj, value) { obj.createdAt = value; } }, metadata: _metadata }, _createdAt_initializers, _instanceExtraInitializers);
        __esDecorate(null, null, _updatedAt_decorators, { kind: "field", name: "updatedAt", static: false, private: false, access: { has: function (obj) { return "updatedAt" in obj; }, get: function (obj) { return obj.updatedAt; }, set: function (obj, value) { obj.updatedAt = value; } }, metadata: _metadata }, _updatedAt_initializers, _instanceExtraInitializers);
        __esDecorate(null, null, _deliveredAt_decorators, { kind: "field", name: "deliveredAt", static: false, private: false, access: { has: function (obj) { return "deliveredAt" in obj; }, get: function (obj) { return obj.deliveredAt; }, set: function (obj, value) { obj.deliveredAt = value; } }, metadata: _metadata }, _deliveredAt_initializers, _instanceExtraInitializers);
        __esDecorate(null, null, _itemsHash_decorators, { kind: "field", name: "itemsHash", static: false, private: false, access: { has: function (obj) { return "itemsHash" in obj; }, get: function (obj) { return obj.itemsHash; }, set: function (obj, value) { obj.itemsHash = value; } }, metadata: _metadata }, _itemsHash_initializers, _instanceExtraInitializers);
        __esDecorate(null, null, _refundedAmount_decorators, { kind: "field", name: "refundedAmount", static: false, private: false, access: { has: function (obj) { return "refundedAmount" in obj; }, get: function (obj) { return obj.refundedAmount; }, set: function (obj, value) { obj.refundedAmount = value; } }, metadata: _metadata }, _refundedAmount_initializers, _instanceExtraInitializers);
        __esDecorate(null, _classDescriptor = { value: _classThis }, _classDecorators, { kind: "class", name: _classThis.name, metadata: _metadata }, null, _classExtraInitializers);
        OrderEntity = _classThis = _classDescriptor.value;
        if (_metadata) Object.defineProperty(_classThis, Symbol.metadata, { enumerable: true, configurable: true, writable: true, value: _metadata });
        __runInitializers(_classThis, _classExtraInitializers);
    })();
    return OrderEntity = _classThis;
}();
exports.OrderEntity = OrderEntity;
