declare module 'class-validator' {
  export type ValidationOptions = any;
  export type ValidationArguments = any;
  export type ValidatorOptions = any;
  export type ValidationError = any;
  export type ValidatorConstraintInterface = any;
  export type ValidationSchema = any;
  export type ValidationTypes = any;

  export function validate(reOrValidatorOptions: any, object: any, options?: any): Promise<any>;
  export function validateSync(reOrValidatorOptions: any, object: any, options?: any): any;
  export function isEmail(string: any, options?: any): boolean;
  export function isString(string: any, options?: any): boolean;
  export function isNumber(string: any, options?: any): boolean;
  export function isInt(string: any, options?: any): boolean;
  export function isBoolean(string: any, options?: any): boolean;
  export function isArray(string: any, options?: any): boolean;
  export function isObject(string: any, options?: any): boolean;
  export function isDate(string: any, options?: any): boolean;
  export function isDateString(string: any, options?: any): boolean;
  export function isEnum<T>(enumType: T, value: any, options?: any): boolean;
  export function isIn(values: any[], value: any, options?: any): boolean;
  export function isOptional(value: any): boolean;
  export function min(min: number, options?: any): (object: any, propertyName: string) => any;
  export function minLength(min: number, options?: any): (object: any, propertyName: string) => any;
  export function maxLength(max: number, options?: any): (object: any, propertyName: string) => any;
  export function validateNested(options?: any): (object: any, propertyName: string) => any;
  export function isUUID(value: any, options?: any): boolean;
  export function isPhoneNumber(value: any, options?: any): boolean;
  export function isJSON(value: any, options?: any): boolean;
  export function isURL(value: any, options?: any): boolean;
  export function isMongoId(value: any): boolean;
  export function isCurrency(value: any, options?: any): boolean;
  export function isISO8601(value: any, options?: any): boolean;
  export function length(length: number, options?: any): (object: any, propertyName: string) => any;
  export function maxLength(max: number, options?: any): (object: any, propertyName: string) => any;
  export function minLength(min: number, options?: any): (object: any, propertyName: string) => any;
  export function matches(pattern: RegExp | string, options?: any): (object: any, propertyName: string) => any;
  export function isAlpha(string: any, options?: any): boolean;
  export function isAlphanumeric(string: any, options?: any): boolean;
  export function isAscii(string: any, options?: any): boolean;
  export function isBase32(string: any, options?: any): boolean;
  export function isBase64(string: any, options?: any): boolean;
  export function isBooleanString(string: any, options?: any): boolean;
  export function isByteLength(string: any, options?: any): boolean;
  export function isCreditCard(string: any, options?: any): boolean;
  export function isCurrency(string: any, options?: any): boolean;
  export function isDataURI(string: any, options?: any): boolean;
  export function isDecimal(string: any, options?: any): boolean;
  export function isDivisibleBy(number: any, options?: any): boolean;
  export function isEmail(string: any, options?: any): boolean;
  export function isFQDN(string: any, options?: any): boolean;
  export function isFullWidth(string: any, options?: any): boolean;
  export function isHalfWidth(string: any, options?: any): boolean;
  export function isHash(string: any, options?: any): boolean;
  export function isHexadecimal(string: any, options?: any): boolean;
  export function isHexColor(string: any, options?: any): boolean;
  export function isIP(string: any, options?: any): boolean;
  export function isISBN(string: any, options?: any): boolean;
  export function isJSON(string: any, options?: any): boolean;
  export function isJWT(string: any, options?: any): boolean;
  export function isLatLong(string: any, options?: any): boolean;
  export function isLatitude(string: any, options?: any): boolean;
  export function isLongitude(string: any, options?: any): boolean;
  export function isLowercase(string: any, options?: any): boolean;
  export function isMobilePhone(string: any, options?: any): boolean;
  export function isMongoId(string: any): boolean;
  export function isMultibyte(string: any, options?: any): boolean;
  export function isNumberString(string: any, options?: any): boolean;
  export function isPositive(number: any, options?: any): boolean;
  export function isNegative(number: any, options?: any): boolean;
  export function isPort(string: any, options?: any): boolean;
  export function isPostalCode(string: any, options?: any): boolean;
  export function isRFC3339(string: any, options?: any): boolean;
  export function isRgbColor(string: any, options?: any): boolean;
  export function isSemVer(string: any, options?: any): boolean;
  export function isStrongPassword(string: any, options?: any): boolean;
  export function isSurrogatePair(string: any, options?: any): boolean;
  export function isTimeZone(string: any, options?: any): boolean;
  export function isUppercase(string: any, options?: any): boolean;
  export function isUrl(string: any, options?: any): boolean;
  export function isVariableWidth(string: any, options?: any): boolean;
  export function isFirebasePushId(string: any): boolean;
  export function isBIC(string: any, options?: any): boolean;
  export function isIBAN(string: any, options?: any): boolean;
  export function isEthereumAddress(string: any, options?: any): boolean;
  export function isISO31661Alpha2(string: any, options?: any): boolean;
  export function isISO31661Alpha3(string: any, options?: any): boolean;
  export function isISO31661Numeric(string: any, options?: any): boolean;
  export function isISRC(string: any, options?: any): boolean;
  export function isISSN(string: any, options?: any): boolean;
  export function isISIN(string: any, options?: any): boolean;
  export function isRFC3339(string: any, options?: any): boolean;
  export function isLocale(string: any, options?: any): boolean;
  export function isMimeType(string: any, options?: any): boolean;
  export function isMobilePhone(string: any, options?: any): boolean;
  export function isEmptyString(string: any, options?: any): boolean;
  export function isDefined(value: any): boolean;
  export function isNotEmpty(value: any): boolean;
  export function isNotIn(values: any[], value: any, options?: any): boolean;
  export function equals(comparedValue: any, options?: any): (object: any, propertyName: string) => any;
  export function notEquals(comparedValue: any, options?: any): (object: any, propertyName: string) => any;
  export function isInstance(object: any, options?: any): boolean;
  export function isNotEmptyObject(object: any, options?: any): boolean;
  export function validateNested(options?: any): any;
  export function ValidateIf(validation: (object: any, value: any) => boolean, options?: any): any;
  export function ValidatePromise(options?: any): any;
  export function ValidateBy(validation: any, options?: any): any;
  export function ValidateNested(options?: any): any;
  export function registerDecorator(options: any): void;
  export function getFromContainer(validatorOptions?: any): any;

  export const ValidatorConstraint: any;
  export const IsEmail: any;
  export const IsString: any;
  export const IsNumber: any;
  export const IsInt: any;
  export const IsBoolean: any;
  export const IsArray: any;
  export const IsObject: any;
  export const IsDate: any;
  export const IsDateString: any;
  export const IsEnum: any;
  export const IsIn: any;
  export const IsOptional: any;
  export const Min: any;
  export const MinLength: any;
  export const MaxLength: any;
  export const ValidateNested: any;
  export const IsUUID: any;
  export const IsPhoneNumber: any;
  export const IsJSON: any;
  export const IsURL: any;
  export const IsMongoId: any;
  export const IsCurrency: any;
  export const IsISO8601: any;
  export const Length: any;
  export const Matches: any;
  export const IsAlpha: any;
  export const IsAlphanumeric: any;
  export const IsAscii: any;
  export const IsBase32: any;
  export const IsBase64: any;
  export const IsBooleanString: any;
  export const IsByteLength: any;
  export const IsCreditCard: any;
  export const IsDataURI: any;
  export const IsDecimal: any;
  export const IsDivisibleBy: any;
  export const IsFQDN: any;
  export const IsFullWidth: any;
  export const IsHalfWidth: any;
  export const IsHash: any;
  export const IsHexadecimal: any;
  export const IsHexColor: any;
  export const IsIP: any;
  export const IsISBN: any;
  export const IsJSON: any;
  export const IsJWT: any;
  export const IsLatLong: any;
  export const IsLatitude: any;
  export const IsLongitude: any;
  export const IsLowercase: any;
  export const IsMultibyte: any;
  export const IsNumberString: any;
  export const IsPositive: any;
  export const IsNegative: any;
  export const IsPort: any;
  export const IsPostalCode: any;
  export const IsRFC3339: any;
  export const IsRgbColor: any;
  export const IsSemVer: any;
  export const IsStrongPassword: any;
  export const IsSurrogatePair: any;
  export const IsTimeZone: any;
  export const IsUppercase: any;
  export const IsUrl: any;
  export const IsVariableWidth: any;
  export const IsFirebasePushId: any;
  export const IsBIC: any;
  export const IsIBAN: any;
  export const IsEthereumAddress: any;
  export const IsISO31661Alpha2: any;
  export const IsISO31661Alpha3: any;
  export const IsISO31661Numeric: any;
  export const IsISRC: any;
  export const IsISSN: any;
  export const IsISIN: any;
  export const IsLocale: any;
  export const IsMimeType: any;
  export const IsEmptyString: any;
  export const IsDefined: any;
  export const IsNotEmpty: any;
  export const IsNotIn: any;
  export const Equals: any;
  export const NotEquals: any;
  export const IsInstance: any;
  export const IsNotEmptyObject: any;
  export const ArrayContains: any;
  export const ArrayNotContains: any;
  export const ArrayNotEmpty: any;
  export const ArrayMaxSize: any;
  export const ArrayMinSize: any;
  export const ArrayUnique: any;
  export const MaxDate: any;
  export const MinDate: any;
  export const Max: any;
  export const Allow: any;
  export const NotEquals: any;
  export const Validate: any;
  export const ValidateBy: any;
  export const ValidateIf: any;
  export const ValidatePromise: any;
  export const ValidateNested: any;
  export const registerDecorator: any;
  export const getFromContainer: any;
}
