declare module 'typeorm' {
  export class DataSource {}
  export class EntityManager {}
  export class EntityTarget<T> {}
  export class Repository<T> {}
  export class SelectQueryBuilder<T> {}
  export class DeleteResult {}
  export class UpdateResult {}
  export class InsertResult {}
  export class QueryFailedOrErrorEvent {}
  export class BaseEntity {}
  export class PrimaryGeneratedColumn {}
  export class Column {}
  export class Entity {}
  export class ManyToOne {}
  export class OneToMany {}
  export class ManyToMany {}
  export class JoinColumn {}
  export class JoinTable {}
  export class Index {}
  export class Unique {}
  export class Check {}
  export class TableInheritance {}
  export class ObjectIdColumn {}
  export class CreateDateColumn {}
  export class UpdateDateColumn {}
  export class DeleteDateColumn {}
  export class VersionColumn {}
  export class Transaction {}
  export class TransactionManager {}
  export class Connection {}
  export class Driver {}
  export class QueryRunner {}
  export class SelectQueryOptions {}
  export class LoadStrategy {}
  export class Between {}
  export class MoreThan {}
  export class LessThan {}
  export class MoreThanOrEqual {}
  export class LessThanOrEqual {}
  export class In {}
  export class IsNull {}
  export class Not {}
  export class Like {}
  export class FindOptionsWhere<T> {}
  export class Raw<T> {}
  export class MigrationInterface {}
}
