"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.STRINGS = void 0;
exports.STRINGS = {
    orderHistory: {
        title: 'Order History',
        loading: 'Loading order history...',
        empty: 'No orders found',
        error: 'Failed to load order history',
        retry: 'Retry',
        backToHome: 'Back to Home',
        status: {
            all: 'All',
            preparing: 'Preparing',
            ready: 'Ready',
            pickedUp: 'Picked Up',
            delivered: 'Delivered',
            cancelled: 'Cancelled',
        },
        items: (count) => `${count} items`,
        total: 'Total:',
        reorder: 'Reorder',
        track: 'Track',
        orderId: (id) => `#${id}`,
        reorderSuccess: 'Items added to cart!',
        reorderError: 'Failed to reorder. Please try again.',
        orderNotFound: 'Order not found',
    },
    cart: {
        title: 'Your Cart',
        loading: 'Loading your cart...',
        empty: 'Your cart is empty',
        emptySubtext: 'Add some delicious food to get started',
        browseRestaurants: 'Browse Restaurants',
        checkout: 'Proceed to Checkout',
        emptyCartAlert: 'Your cart is empty',
        emptyCartAlertSubtext: 'Add items to your cart before proceeding to checkout.',
        signInRequired: 'Sign In Required',
        signInRequiredSubtext: 'Please sign in to continue checkout.',
        loginRequired: 'Login Required',
        checkoutError: 'Checkout Error',
        signIn: 'Sign In',
        cancel: 'Cancel',
        profileSaveSuccess: 'Profile saved successfully!',
        profileSaveError: 'Failed to save profile. Please try again.',
        logoutSuccess: 'You have been logged out.',
    },
    accessibility: {
        loading: 'Loading content',
        backButton: 'Go back',
        reorderButton: 'Reorder this order',
        trackButton: 'Track this order',
        filterTab: (status) => `Filter by ${status} orders`,
        orderCard: (restaurant, status) => `Order from ${restaurant}, ${status} status`,
        orderItems: (count) => `${count} items in this order`,
        decreaseQuantity: (name) => `Decrease ${name} quantity`,
        increaseQuantity: (name) => `Increase ${name} quantity`,
        removeFromCart: (name) => `Remove ${name} from cart`,
        checkout: 'Proceed to checkout',
        removeItemConfirm: 'Remove from cart',
        removeItemConfirmSubtext: 'Are you sure you want to remove this item?',
        remove: 'Remove',
        cartItem: (name, quantity) => `${name}, quantity ${quantity}`,
    },
    navigation: {
        auth: 'Auth',
        main: 'Main',
        home: 'Home',
        search: 'Search',
        cart: 'Cart',
        profile: 'Profile',
        tracking: 'Tracking',
        orderDetails: 'OrderDetails',
        checkout: 'Checkout',
    },
};
