export const STRINGS = {
  orderHistory: {
    title: 'Order History',
    loading: 'Loading order history...',
    empty: 'No orders found',
    error: 'Failed to load order history',
    retry: 'Retry',
    backToHome: 'Back to Home',
    status: {
      all: 'All',
      preparing: 'Preparing',
      ready: 'Ready',
      pickedUp: 'Picked Up',
      delivered: 'Delivered',
      cancelled: 'Cancelled',
    },
    items: (count: number) => `${count} items`,
    total: 'Total:',
    reorder: 'Reorder',
    track: 'Track',
    orderId: (id: string) => `#${id}`,
    reorderSuccess: 'Items added to cart!',
    reorderError: 'Failed to reorder. Please try again.',
    orderNotFound: 'Order not found',
  },
  cart: {
    title: 'Your Cart',
    loading: 'Loading your cart...',
    empty: 'Your cart is empty',
    emptySubtext: 'Add some delicious food to get started',
    browseRestaurants: 'Browse Restaurants',
    checkout: 'Proceed to Checkout',
    emptyCartAlert: 'Your cart is empty',
    emptyCartAlertSubtext: 'Add items to your cart before proceeding to checkout.',
    signInRequired: 'Sign In Required',
    signInRequiredSubtext: 'Please sign in to continue checkout.',
    loginRequired: 'Login Required',
    checkoutError: 'Checkout Error',
    signIn: 'Sign In',
    cancel: 'Cancel',
    profileSaveSuccess: 'Profile saved successfully!',
    profileSaveError: 'Failed to save profile. Please try again.',
    logoutSuccess: 'You have been logged out.',
  },
  accessibility: {
    loading: 'Loading content',
    backButton: 'Go back',
    reorderButton: 'Reorder this order',
    trackButton: 'Track this order',
    filterTab: (status: string) => `Filter by ${status} orders`,
    orderCard: (restaurant: string, status: string) => `Order from ${restaurant}, ${status} status`,
    orderItems: (count: number) => `${count} items in this order`,
    decreaseQuantity: (name: string) => `Decrease ${name} quantity`,
    increaseQuantity: (name: string) => `Increase ${name} quantity`,
    removeFromCart: (name: string) => `Remove ${name} from cart`,
    checkout: 'Proceed to checkout',
    removeItemConfirm: 'Remove from cart',
    removeItemConfirmSubtext: 'Are you sure you want to remove this item?',
    remove: 'Remove',
    cartItem: (name: string, quantity: number) => `${name}, quantity ${quantity}`,
    legal: {
      loading: 'Loading legal document',
      backButton: 'Go back',
      retryButton: 'Retry loading document',
      privacyPolicy: 'Read Privacy Policy',
      termsOfService: 'Read Terms of Service',
      cookiePolicy: 'Read Cookie Policy',
      dataRetentionPolicy: 'Read Data Retention Policy',
      securityCenter: 'Visit Security Center',
    },
    privacy: {
      loading: 'Loading privacy settings',
      backButton: 'Go back',
      consentActive: 'Privacy settings are active',
      necessaryToggle: 'Necessary cookies toggle',
      analyticsToggle: 'Analytics cookies toggle',
      marketingToggle: 'Marketing cookies toggle',
      functionalToggle: 'Functional cookies toggle',
      requestAccess: 'Request access to your data',
      deleteData: 'Request deletion of your data',
      exportJson: 'Export data as JSON',
      exportCsv: 'Export data as CSV',
    },
  },
  wallet: {
    title: 'Wallet',
    balanceLabel: 'Available Balance',
    addMoney: 'Add Money',
    enterAmount: 'Enter amount',
    addMoneySuccess: 'Money added successfully!',
    addMoneyError: 'Failed to add money. Please try again.',
    loading: 'Loading wallet...',
    empty: 'No transactions yet',
    emptySubtext: 'Your wallet activity will appear here.',
    retry: 'Retry',
    backToHome: 'Back to Home',
    viewAll: 'View all transactions',
    type: {
      credit: 'Added',
      debit: 'Debited',
      refund: 'Refund',
      cashback: 'Cashback',
      order_payment: 'Order Payment',
      cod_collection: 'COD Collected',
      compensation: 'Compensation',
    },
  },
  navigation: {
    auth: 'Auth',
    main: 'Main',
    home: 'Home',
    search: 'Search',
    cart: 'Cart',
    profile: 'Profile',
    tracking: 'Tracking',
    orderDetails: 'OrderDetails',
    checkout: 'Checkout',
  },
} as const;

export type StringsKey = keyof typeof STRINGS;
export type StatusKey = keyof typeof STRINGS.orderHistory.status;