module.exports = {
  View: 'View',
  Text: 'Text',
  TextInput: 'TextInput',
  TouchableOpacity: 'TouchableOpacity',
  Pressable: 'Pressable',
  ScrollView: 'ScrollView',
  SafeAreaView: 'SafeAreaView',
  Image: 'Image',
  ActivityIndicator: 'ActivityIndicator',
  Animated: {
    Value: jest.fn((value) => ({ value, interpolate: jest.fn(() => ({ interpolate: jest.fn() })), stopAnimation: jest.fn() })),
    timing: jest.fn(() => ({ start: jest.fn() })),
    spring: jest.fn(() => ({ start: jest.fn() })),
    sequence: jest.fn(() => ({ start: jest.fn() })),
    parallel: jest.fn(() => ({ start: jest.fn() })),
    delay: jest.fn(() => 'delay'),
    createAnimatedComponent: (component) => component,
    View: 'Animated.View',
  },
  Easing: {
    linear: jest.fn(() => 'linear'),
    ease: jest.fn(() => 'ease'),
    quad: jest.fn(() => 'quad'),
    cubic: jest.fn(() => 'cubic'),
    poly: jest.fn(() => 'poly'),
    sin: jest.fn(() => 'sin'),
    circle: jest.fn(() => 'circle'),
    exp: jest.fn(() => 'exp'),
    elastic: jest.fn(() => 'elastic'),
    bounce: jest.fn(() => 'bounce'),
    back: jest.fn(() => 'back'),
    in: jest.fn(() => 'in'),
    out: jest.fn(() => 'out'),
    inOut: jest.fn(() => 'inOut'),
  },
  FlatList: ({ data, renderItem, keyExtractor }) => {
    const React = require('react');
    return React.createElement(
      React.Fragment,
      null,
      ...data.map((item, index) => React.createElement(
        React.Fragment,
        { key: keyExtractor ? keyExtractor(item, index) : index },
        renderItem({ item, index }),
      )),
    );
  },
  Modal: 'Modal',
  Switch: 'Switch',
  StatusBar: 'StatusBar',
  KeyboardAvoidingView: 'KeyboardAvoidingView',
  Keyboard: {
    addListener: jest.fn(() => ({ remove: jest.fn() })),
    removeListener: jest.fn(),
  },
  RefreshControl: 'RefreshControl',
  TouchableWithoutFeedback: 'TouchableWithoutFeedback',
  TouchableHighlight: 'TouchableHighlight',
  Alert: { alert: jest.fn() },
  Linking: { openURL: jest.fn() },
  Dimensions: { get: jest.fn(() => ({ width: 390, height: 844, scale: 1, fontScale: 1 })) },
  PixelRatio: { get: jest.fn(() => 1) },
  Appearance: { getColorScheme: jest.fn(() => 'light') },
  I18nManager: {
    isRTL: false,
    getConstants: jest.fn(() => ({ isRTL: false })),
  },
  StyleSheet: {
    create: (styles) => styles,
    flatten: (style) => Array.isArray(style) ? Object.assign({}, ...style.filter(Boolean)) : style || {},
    hairlineWidth: 1,
    select: (styles) => styles?.default || styles,
  },
  Platform: {
    OS: 'ios',
    select: (specs) => specs?.default || specs?.ios || specs?.android,
  },
};
